# Generated by Django 4.1.3 on 2022-11-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clasific', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=150)),
                ('supplier', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Moto',
        ),
    ]
