# Generated by Django 4.1.3 on 2022-11-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produc', '0002_produc_delete_moto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produc',
            old_name='nom',
            new_name='name',
        ),
    ]
